# Generated by Django 4.2.4 on 2023-09-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=220)),
                ('budget', models.PositiveBigIntegerField()),
                ('employment', models.PositiveBigIntegerField()),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
